### PR TITLE
upgrade to node16

### PR DESCRIPTION
**Pull request by vpipkt**
👋🏽thanks for contributing, here's a short checklist to complete:

- [ ] added tests for all the new/modified features
- [ ] all CI checks are passing
- [x] commited the latest compiled `dits/index.js`
- [x] updated the cods wherever appropriate
- [x] link to any related issues/PRs
- [ ] add appropriate labels: enhancement, bug, etc.
- [ ] add `@titoine54` and `@camilogarcialarotta` as reviewers

### What
Upgrade to node 16 to avoid breaking workflows. See [github announcement](https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/
).

### CODE REVIEW

**Comment by vpipkt** [comment]
@titoine54 and @CamiloGarciaLaRotta I am unable to add you as reviewers or change labesl.  I would appreciate a look at this PR. 🙏

**Comment by vpipkt** [comment]
Checks have run [in my fork](https://github.com/vpipkt/watermelon-http-client/actions). 

The [OSSAR scan](https://github.com/vpipkt/watermelon-http-client/actions/runs/3271544505) fails and I am not sure how to address it.

There are also plenty of error and warning messages, but I think they are not an issue. Have a look and let me know.

**Comment by CamiloGarciaLaRotta** [comment]
oh hey! thanks for this contribition @vpipkt I had not been in GH for a while 😅 

Lemme pull your branch locally and bundle it. That `index.js` diff is quite large to review manually, so if I get the same build I'm happy to approve

**Comment by CamiloGarciaLaRotta** [comment]
🙌🏼 awesome, thank you

**Pull request merged**
